name: Continuous Integration

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [18, 20, 22]
    runs-on: ${{ matrix.os }}
    env:
      DEBUG: sdk:watchFs
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run test
        run: pnpm test
